"""empty message

Revision ID: 9cd536373024
Revises: b1e43209f49f
Create Date: 2026-05-28 14:02:23.843754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd536373024'
down_revision: Union[str, Sequence[str], None] = 'b1e43209f49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('contact_uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deals',
    sa.Column('deal_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progres', 'expired', 'finished', 'not_started', name='status'), nullable=False),
    sa.Column('contact_uuid', sa.UUID(), nullable=False),
    sa.Column('owner_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contact_uuid'], ['contacts.contact_uuid'], ),
    sa.ForeignKeyConstraint(['owner_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('deal_uuid')
    )
    op.create_table('tasks',
    sa.Column('task_uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointed', sa.UUID(), nullable=False),
    sa.Column('deal', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointed'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['deal'], ['deals.deal_uuid'], ),
    sa.PrimaryKeyConstraint('task_uuid'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('deals')
    op.drop_table('contacts')
    # ### end Alembic commands ###
